plugins {
    id "architectury-plugin" version "3.5.169"
    id "dev.architectury.loom" version "1.17.491" apply false
    id "org.jetbrains.kotlin.jvm" version "$kotlin_version" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

ext.modMetadata = [
        mod_id                  : mod_id,
        mod_name                : mod_name,
        mod_version             : mod_version,
        mod_description         : mod_description,
        mod_author              : mod_author,
        mod_license             : mod_license,
        mod_homepage            : mod_homepage,
        mod_issues              : mod_issues,
        java_version            : java_version,
        minecraft_version       : minecraft_version,
        architectury_version    : architectury_version,
        fabric_loader_version   : fabric_loader_version,
        fabric_kotlin_version   : fabric_kotlin_version,
        neoforge_version        : neoforge_version,
        kotlin_for_forge_version: kotlin_for_forge_version,
]

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"

    version = "${rootProject.mod_version}+${rootProject.minecraft_version}"
    group = rootProject.maven_group

    repositories {
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.neoforged.net/releases/" }
        maven {
            name = "Kotlin for Forge"
            url = "https://thedarkcolour.github.io/KotlinForForge/"
            content { includeGroup "thedarkcolour" }
        }
        ivy {
            name = "Vendored"
            url = rootProject.file("libs")
            patternLayout { artifact "[artifact]-[revision].jar" }
            metadataSources { artifact() }
            content { includeGroup "vendor" }
        }
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version as int)
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = rootProject.java_version as int
    }
}

subprojects {
    apply plugin: "org.jetbrains.kotlin.jvm"
    apply plugin: "dev.architectury.loom"

    base {
        archivesName = "${rootProject.archives_name}-${project.name}"
    }

    loom {
        silentMojangMappingsLicense()
    }

    kotlin {
        jvmToolchain(rootProject.java_version as int)
    }

    def javaOutput = tasks.named("compileJava", JavaCompile).map { it.destinationDirectory }
    tasks.named("classes").configure {
        doLast { javaOutput.get().get().asFile.mkdirs() }
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()
        compileOnly "org.jetbrains.kotlin:kotlin-stdlib:${rootProject.kotlin_version}"
    }
}
